const data = [
    {
      "idCompra": "09000906900072025",
      "numeroControlePNCP": "00508903000188-1-000900/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 900,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "90007",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 4,
      "codigoModoDisputa": 4,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Art. 75º, Inciso II da Lei nº 14.133 de 1º/04/2021.",
      "processo": "0000097-51.2025.4",
      "objetoCompra": "O objeto da presente dispensa é a escolha da proposta mais vantajosa para aquisição de cinto tático, conforme condições, quantidades e exigências estabelecidas neste Aviso de Contratação Direta e seus anexos.",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 2,
      "tipoInstrumentoConvocatorioNome": "Aviso de Contratação Direta",
      "modoDisputaNomePncp": "Dispensa Com Disputa",
      "valorTotalEstimado": 7064.25,
      "valorTotalHomologado": 5439.25,
      "dataInclusaoPncp": "2025-05-05T14:53:56",
      "dataAtualizacaoPncp": "2025-05-05T14:53:56",
      "dataPublicacaoPncp": "2025-05-05T14:53:56",
      "dataAberturaPropostaPncp": "2025-05-05T14:53:55",
      "dataEncerramentoPropostaPncp": "2025-05-08T07:59:59",
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906900082025",
      "numeroControlePNCP": "00508903000188-1-001181/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 1181,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "90008",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 4,
      "codigoModoDisputa": 4,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Art. 75º, Inciso II da Lei nº 14.133 de 1º/04/2021.",
      "processo": "0002292-09.2025.4",
      "objetoCompra": "O objeto da presente dispensa é a escolha da proposta mais vantajosa para execução de serviços de manutenção preventiva única do sistema de climatização, tipo VRF, da Subseção Judiciária de Caruaru, conforme condições, quantidades e exigências estabelecidas neste Aviso de Contratação Direta e seus anexos. ",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 2,
      "tipoInstrumentoConvocatorioNome": "Aviso de Contratação Direta",
      "modoDisputaNomePncp": "Dispensa Com Disputa",
      "valorTotalEstimado": 24575.09,
      "valorTotalHomologado": 18950,
      "dataInclusaoPncp": "2025-05-29T15:37:30",
      "dataAtualizacaoPncp": "2025-05-29T15:37:30",
      "dataPublicacaoPncp": "2025-05-29T15:37:30",
      "dataAberturaPropostaPncp": "2025-05-29T15:37:28",
      "dataEncerramentoPropostaPncp": "2025-06-03T07:59:59",
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906000222025",
      "numeroControlePNCP": "00508903000188-1-001518/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 1518,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "22",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 5,
      "codigoModoDisputa": 5,
      "amparoLegalCodigoPncp": 38,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, VIII",
      "amparoLegalDescricao": "Dispensa de Licitação: nos casos de emergência ou de calamidade pública, quando caracterizada urgência de atendimento de situação que possa ocasionar prejuízo ou comprometer a continuidade dos serviços públicos ou a segurança de pessoas, obras, serviços, equipamentos e outros bens, públicos ou particulares, e somente para aquisição dos bens necessários ao atendimento da situação emergencial ou calamitosa e para as parcelas de obras e serviços que possam ser concluídas no prazo máximo de 1 (um) ano, contado da data de ocorrência da emergência ou da calamidade, vedadas a prorrogação dos respectivos contratos e a recontratação de empresa já contratada com base no disposto neste inciso",
      "informacaoComplementar": "O sistema de climatização do edifício, composto pelo chiller responsável pela refrigeração, apresentou defeito. Para o correto funcionamento e eficiência do equipamento, é imprescindível a reposição do gás refrigerante específico, conforme especificação técnica do fabricante.\n\nA falta do gás compromete a capacidade de resfriamento, o que pode impactar negativamente no conforto ambiental, na produtividade dos colaboradores, servidores e jurisdicionados e no funcionamento adequado das instalações. Além disso, a manutenção do chiller é essencial para evitar danos maiores ao equipamento, que poderiam resultar em custos ainda mais elevados com reparos ou substituição.\n\nPortanto, a aquisição do gás refrigerante se faz necessária para a rápida recuperação do sistema, garantindo a climatização adequada do ambiente, a preservação do equipamento e a continuidade das operações com segurança e eficiência.\n\nInterrupções no sistema de ar condicionado podem impactar negativamente a realização das audiências. A falta de um chiller funcional pode levar ao desconforto dos participantes e até mesmo à impossibilidade de realizar procedimentos devido a condições inadequadas.",
      "processo": "0003493-36.2025.4.05.7500",
      "objetoCompra": "Gás refrigerante R134A, cilindro de 13 kg, puro, ou seja, de primeiro uso, não reciclado.",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 3,
      "tipoInstrumentoConvocatorioNome": "Ato que autoriza a Contratação Direta",
      "modoDisputaNomePncp": "Não se aplica",
      "valorTotalEstimado": 21750,
      "valorTotalHomologado": 21750,
      "dataInclusaoPncp": "2025-07-09T14:19:04",
      "dataAtualizacaoPncp": "2025-07-09T14:19:04",
      "dataPublicacaoPncp": "2025-07-09T14:19:04",
      "dataAberturaPropostaPncp": null,
      "dataEncerramentoPropostaPncp": null,
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906000172025",
      "numeroControlePNCP": "00508903000188-1-000416/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 416,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "17",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 5,
      "codigoModoDisputa": 5,
      "amparoLegalCodigoPncp": 38,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, VIII",
      "amparoLegalDescricao": "Dispensa de Licitação: nos casos de emergência ou de calamidade pública, quando caracterizada urgência de atendimento de situação que possa ocasionar prejuízo ou comprometer a continuidade dos serviços públicos ou a segurança de pessoas, obras, serviços, equipamentos e outros bens, públicos ou particulares, e somente para aquisição dos bens necessários ao atendimento da situação emergencial ou calamitosa e para as parcelas de obras e serviços que possam ser concluídas no prazo máximo de 1 (um) ano, contado da data de ocorrência da emergência ou da calamidade, vedadas a prorrogação dos respectivos contratos e a recontratação de empresa já contratada com base no disposto neste inciso",
      "informacaoComplementar": null,
      "processo": "0001210-40.2025.4.05.7500",
      "objetoCompra": "Serviços de reparo no algeroz do anexo 1 ao edifício-sede",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 3,
      "tipoInstrumentoConvocatorioNome": "Ato que autoriza a Contratação Direta",
      "modoDisputaNomePncp": "Não se aplica",
      "valorTotalEstimado": 18431.8,
      "valorTotalHomologado": 18431.8,
      "dataInclusaoPncp": "2025-02-27T12:34:45",
      "dataAtualizacaoPncp": "2025-02-27T12:34:45",
      "dataPublicacaoPncp": "2025-02-27T12:34:45",
      "dataAberturaPropostaPncp": null,
      "dataEncerramentoPropostaPncp": null,
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906000132025",
      "numeroControlePNCP": "00508903000188-1-000092/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 92,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "13",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 5,
      "codigoModoDisputa": 5,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Artigo 22 da IN 67/2021 (inciso III)",
      "processo": "0006932-89.2024.4.05.7500",
      "objetoCompra": "ÁGUA MINERAL SEM GÁS (PARTICIPAÇÃO RESTRITA A MICROEMPRESAS E EMPRESAS DE PEQUENO PORTE) marca: Serra Branca. - Local de entrega: Subseção Judiciária de Garanhuns, situada na R. Vital Brasil, n.º 44, Novo Heliópolis, Garanhuns-PE.",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 3,
      "tipoInstrumentoConvocatorioNome": "Ato que autoriza a Contratação Direta",
      "modoDisputaNomePncp": "Não se aplica",
      "valorTotalEstimado": 4734,
      "valorTotalHomologado": 4734,
      "dataInclusaoPncp": "2025-01-15T13:49:51",
      "dataAtualizacaoPncp": "2025-01-15T13:49:51",
      "dataPublicacaoPncp": "2025-01-15T13:49:51",
      "dataAberturaPropostaPncp": null,
      "dataEncerramentoPropostaPncp": null,
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906000202025",
      "numeroControlePNCP": "00508903000188-1-001038/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 1038,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "20",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 5,
      "codigoModoDisputa": 5,
      "amparoLegalCodigoPncp": 38,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, VIII",
      "amparoLegalDescricao": "Dispensa de Licitação: nos casos de emergência ou de calamidade pública, quando caracterizada urgência de atendimento de situação que possa ocasionar prejuízo ou comprometer a continuidade dos serviços públicos ou a segurança de pessoas, obras, serviços, equipamentos e outros bens, públicos ou particulares, e somente para aquisição dos bens necessários ao atendimento da situação emergencial ou calamitosa e para as parcelas de obras e serviços que possam ser concluídas no prazo máximo de 1 (um) ano, contado da data de ocorrência da emergência ou da calamidade, vedadas a prorrogação dos respectivos contratos e a recontratação de empresa já contratada com base no disposto neste inciso",
      "informacaoComplementar": null,
      "processo": "0002605-67.2025.4.05.7500",
      "objetoCompra": "Contratação emergencial dos serviços de IMPERMEABILIZAÇÃO  no telhamento da coberta do bloco B da Subseção Judiciária de Caruaru",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 3,
      "tipoInstrumentoConvocatorioNome": "Ato que autoriza a Contratação Direta",
      "modoDisputaNomePncp": "Não se aplica",
      "valorTotalEstimado": 31496.2,
      "valorTotalHomologado": 31496.2,
      "dataInclusaoPncp": "2025-05-16T14:10:44",
      "dataAtualizacaoPncp": "2025-05-16T14:10:44",
      "dataPublicacaoPncp": "2025-05-16T14:10:44",
      "dataAberturaPropostaPncp": null,
      "dataEncerramentoPropostaPncp": null,
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906900092025",
      "numeroControlePNCP": "00508903000188-1-001260/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 1260,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "90009",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 4,
      "codigoModoDisputa": 4,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Justifica-se em virtude do baixo valor e celeridade do procedimento de dispensa de licitação.",
      "processo": "1077-95.2025.4.05",
      "objetoCompra": "Escolha da proposta mais vantajosa para aquisição de material hospitalar e farmacológico, conforme condições, e exigências estabelecidas no Aviso de Contratação Direta e seus anexos nº 90008/2025",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 2,
      "tipoInstrumentoConvocatorioNome": "Aviso de Contratação Direta",
      "modoDisputaNomePncp": "Dispensa Com Disputa",
      "valorTotalEstimado": 9392.75,
      "valorTotalHomologado": 6907.3345,
      "dataInclusaoPncp": "2025-06-06T15:11:22",
      "dataAtualizacaoPncp": "2025-06-06T15:11:22",
      "dataPublicacaoPncp": "2025-06-06T15:11:22",
      "dataAberturaPropostaPncp": "2025-06-06T15:11:19",
      "dataEncerramentoPropostaPncp": "2025-06-12T07:59:59",
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906900102025",
      "numeroControlePNCP": "00508903000188-1-001415/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 1415,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "90010",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 4,
      "codigoModoDisputa": 4,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Art. 75º, Inciso II da Lei nº 14.133 de 1º/04/2021.",
      "processo": "0003298-51.2025.4",
      "objetoCompra": "O objeto da presente dispensa é a escolha da proposta mais vantajosa para aquisição de placa para substituir a atual, danificada pelo tempo de uso, localizada no edifício sede da Justiça Federal de Primeiro Grau em Pernambuco, conforme condições, quantidades e exigências estabelecidas neste Aviso de Contratação Direta e seus anexos. ",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 2,
      "tipoInstrumentoConvocatorioNome": "Aviso de Contratação Direta",
      "modoDisputaNomePncp": "Dispensa Com Disputa",
      "valorTotalEstimado": 7700,
      "valorTotalHomologado": 6800,
      "dataInclusaoPncp": "2025-06-27T14:40:19",
      "dataAtualizacaoPncp": "2025-06-27T14:40:19",
      "dataPublicacaoPncp": "2025-06-27T14:40:19",
      "dataAberturaPropostaPncp": "2025-06-27T14:40:18",
      "dataEncerramentoPropostaPncp": "2025-07-02T07:59:59",
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906900032025",
      "numeroControlePNCP": "00508903000188-1-000354/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 354,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "90003",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 4,
      "codigoModoDisputa": 4,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "Art. 75º, Inciso II da Lei nº 14.133 de 1º/04/2021.",
      "processo": "0007789-38.2024.4",
      "objetoCompra": "O objeto da presente dispensa é a escolha da proposta mais vantajosa para aquisição de mangueira hidráulica, a ser utilizado, especificamente, na máquina de limpeza da fachada (Lavadora de alta pressão karcher HD7/15 Maxi) do edifício-sede da Justiça Federal de Primeiro Grau em Pernambuco, conforme condições, quantidades e exigências estabelecidas neste Aviso de Contratação Direta e seus anexos.",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 2,
      "tipoInstrumentoConvocatorioNome": "Aviso de Contratação Direta",
      "modoDisputaNomePncp": "Dispensa Com Disputa",
      "valorTotalEstimado": 8178,
      "valorTotalHomologado": 1899,
      "dataInclusaoPncp": "2025-02-19T09:46:24",
      "dataAtualizacaoPncp": "2025-02-19T09:46:24",
      "dataPublicacaoPncp": "2025-02-19T09:46:24",
      "dataAberturaPropostaPncp": "2025-02-19T09:46:23",
      "dataEncerramentoPropostaPncp": "2025-02-24T07:59:59",
      "contratacaoExcluida": false
    },
    {
      "idCompra": "09000906000142025",
      "numeroControlePNCP": "00508903000188-1-000114/2025",
      "anoCompraPncp": 2025,
      "sequencialCompraPncp": 114,
      "orgaoEntidadeCnpj": "00508903000188",
      "orgaoSubrogadoCnpj": null,
      "codigoOrgao": 87693,
      "orgaoEntidadeRazaoSocial": "JUSTICA FEDERAL DE PRIMEIRA INSTANCIA",
      "orgaoSubrogadoRazaoSocial": null,
      "orgaoEntidadeEsferaId": "F",
      "orgaoSubrogadoEsferaId": null,
      "orgaoEntidadePoderId": "J",
      "orgaoSubrogadoPoderId": null,
      "unidadeOrgaoCodigoUnidade": "090009",
      "unidadeSubrogadaCodigoUnidade": null,
      "unidadeOrgaoNomeUnidade": "JUSTICA FEDERAL DE 1A. INSTANCIA - PE",
      "unidadeSubrogadaNomeUnidade": null,
      "unidadeOrgaoUfSigla": "PE",
      "unidadeSubrogadaUfSigla": null,
      "unidadeOrgaoMunicipioNome": "RECIFE",
      "unidade_subrogada_municipio_nome": null,
      "unidadeOrgaoCodigoIbge": 2611606,
      "unidadeSubrogadaCodigoIbge": null,
      "numeroCompra": "14",
      "modalidadeIdPncp": 8,
      "codigoModalidade": 6,
      "modalidadeNome": "Dispensa",
      "srp": false,
      "modoDisputaIdPncp": 5,
      "codigoModoDisputa": 5,
      "amparoLegalCodigoPncp": 19,
      "amparoLegalNome": "Lei 14.133/2021, Art. 75, II",
      "amparoLegalDescricao": "Dispensa de Licitação: para contratação que envolva valores inferiores a R$ 50.000,00 (cinquenta mil reais), no caso de outros serviços e compras",
      "informacaoComplementar": "ÁGUA MINERAL SEM GÁS (PARTICIPAÇÃO RESTRITA A MICROEMPRESAS E EMPRESAS DE PEQUENO PORTE): com as seguintes características:\n\na) acondicionada em garrafão de polipropileno de 20 (vinte) litros, marca: SÃO BENEDITO, com lacre, rótulos e selos fiscais intactos;\n\nb) embalagem retornável de acordo com especificações da Agência Nacional de Vigilância Sanitária - ANVISA/MS:\n\nc) rótulo aprovado pelo Departamento Nacional de Produção Mineral – DNPM, em conformidade com a Portaria 470/99.\n\n- Local de entrega: Subseção Judiciária de Palmares, situada na R. Quilombo dos Palmares, n.º 555, Centro, Palmares-PE.\n\nNota de empenho: 2024NE000560",
      "processo": "0006943-21.2024.4.05.7500",
      "objetoCompra": "Fornecimento de ÁGUA MINERAL NATURAL, SEM GÁS, ACONDICIONADA EM GARRAFÃO DE POLIPROPILENO, CONTENDO NO MÍNIMO 19.5 LITROS PARA A SUBSEÇÃO JUDICIÁRIA DE PALMARES. MARCA: SÃO BENEDITO.",
      "existeResultado": true,
      "orcamentoSigilosoCodigo": 1,
      "orcamentoSigilosoDescricao": "Compra sem sigilo",
      "situacaoCompraIdPncp": 1,
      "situacaoCompraNomePncp": "Divulgada no PNCP",
      "tipoInstrumentoConvocatorioCodigoPncp": 3,
      "tipoInstrumentoConvocatorioNome": "Ato que autoriza a Contratação Direta",
      "modoDisputaNomePncp": "Não se aplica",
      "valorTotalEstimado": 6900,
      "valorTotalHomologado": 6900,
      "dataInclusaoPncp": "2025-01-17T11:13:47",
      "dataAtualizacaoPncp": "2025-01-17T11:13:47",
      "dataPublicacaoPncp": "2025-01-17T11:13:47",
      "dataAberturaPropostaPncp": null,
      "dataEncerramentoPropostaPncp": null,
      "contratacaoExcluida": false
    }
  ]